name: jt2022_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  timelines: ^0.1.0
  calendar_timeline: ^1.0.4
  google_maps_flutter: ^2.1.2
  lottie: ^1.2.2
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  introduction_screen: ^3.0.0
  # google_nav_bar: ^5.0.5
  # curved_navigation_bar: ^1.0.3  
  # dot_navigation_bar: ^1.0.1+4
  # salomon_bottom_bar: ^3.2.0
  line_icons: ^2.0.0
  animated_login: ^1.5.1

  # App Icon
  # flutter_launcher_icons: ^0.9.2
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

  # Firebase Stuff
  firebase_core: ^1.12.0

  # Database
  cloud_firestore: ^3.1.8

  # Authorization
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.4

  # Analytics
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.1
  firebase_performance: ^0.8.0+5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:     
    - assets/images/
    - assets/lottie/
    - assets/icon/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaBold.ttf
        - asset: assets/fonts/LufgaRegular.ttf
