class Churches {
  List regions = [
    {'label': 'Bern Süd', 'value': 'Bern Süd'},
    {'label': 'Thun', 'value': 'Thun'},
    {'label': 'Winterthur', 'value': 'Winterthur'},
    {'label': 'Graubünden', 'value': 'Graubünden'},
    {'label': 'Salzburg', 'value': 'Salzburg'},
    {'label': 'Voralberg', 'value': 'Voralberg'},
    {'label': 'Linz', 'value': 'Linz'},
    {'label': 'Tirol', 'value': 'Tirol'},
  ];

  List municipalities = [
    {'label': 'Bern Ostermundigen', 'value': 'Bern Ostermundigen'},
    {'label': 'Bern Bümpliz', 'value': 'Bern Bümpliz'},
    {'label': 'Zollikofen', 'value': 'Zollikofen'},
    {'label': 'Belp', 'value': 'Belp'},
    {'label': 'Worb', 'value': 'Worb'},
    {'label': 'Neuenegg', 'value': 'Neuenegg'},
    {'label': 'Riggisberg', 'value': 'Riggisberg'},
    {'label': 'Schwarzenburg', 'value': 'Schwarzenburg'},
    {'label': 'Murten', 'value': 'Murten'},
    {'label': 'Thun', 'value': 'Thun'},
    {'label': 'Steffisburg', 'value': 'Steffisburg'},
    {'label': 'Heimenschwand', 'value': 'Heimenschwand'},
    {'label': 'Spiez', 'value': 'Spiez'},
    {'label': 'Zweisimmen', 'value': 'Zweisimmen'},
    {'label': 'Interlaken', 'value': 'Interlaken'},
    {'label': 'Winterthur', 'value': 'Winterthur'},
    {
      'label': 'Winterthur-Oberwinterthur',
      'value': 'Winterthur-Oberwinterthur'
    },
    {'label': 'Rikon', 'value': 'Rikon'},
    {'label': 'Effretikon', 'value': 'Effretikon'},
    {'label': 'Rorbas', 'value': 'Rorbas'},
    {'label': 'Elgg', 'value': 'Elgg'},
    {'label': 'Andelfingen', 'value': 'Andelfingen'},
    {'label': 'Bauma', 'value': 'Bauma'},
    {'label': 'Thusis', 'value': 'Thusis'},
    {'label': 'Chur', 'value': 'Chur'},
    {'label': 'Davos', 'value': 'Davos'},
    {'label': 'Samedan', 'value': 'Samedan'},
    {'label': 'Salzburg', 'value': 'Salzburg'},
    {'label': 'Bad Ischl', 'value': 'Bad Ischl'},
    {'label': 'Bischofshofen', 'value': 'Bischofshofen'},
    {'label': 'Bludenz', 'value': 'Bludenz'},
    {'label': 'Bregenz', 'value': 'Bregenz'},
    {'label': 'Dornbirn', 'value': 'Dornbirn'},
    {'label': 'Götzis', 'value': 'Götzis'},
    {'label': 'Linz-Urfahr', 'value': 'Linz-Urfahr'},
    {'label': 'Linz', 'value': 'Linz'},
    {'label': 'Mauthausen', 'value': 'Mauthausen'},
    {'label': 'Wels', 'value': 'Wels'},
    {'label': 'Steyr', 'value': 'Steyr'},
    {'label': 'Innsbruck', 'value': 'Innsbruck'},
    {'label': 'Jenbach', 'value': 'Jenbach'},
    {'label': 'Mayrhofen', 'value': 'Mayrhofen'},
    {'label': 'Telfs', 'value': 'Telfs'},
    {'label': 'Kirchbichl', 'value': 'Kirchbichl'},
  ];
}
